### ISSUE TITLE
Store Entries Checklist

### ISSUE THREAD

**Issue by UndeadZeratul** [HDest-Community/Merchant#2]
Especially since things can be simply turned off via CVARs now, why not just add support for literally everything and let players decide what they don't want to be sold?

- [ ] Remaining vanilla weapons
- [ ] Magazines
- [x] URL Crafting Materials & Gunsmith Pouch
- [x] Cozi's Offworld Wares
- [ ] Renegade's weapons/items
- [ ] Potetobloke's Riot Shield
- [x] Altis O/U Shotgun
- [ ] UaS LLM
- [x] Gearbox Container
- [ ] Shield Cores
- [ ] Blurspheres
- [ ] Nora
- [ ] Reusable Ammoboxes
- [ ] ERPs
- [ ] Operation: Dead Ringer
- [ ] Hand-cranked Cell Charger & Micro-Cell Charger
- [ ] 4.26mm Bulk Box
- [ ] Cybercool's UaS Alcohol
